/* Generated By:JJTree: Do not edit this line. ArgList_Assign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ArgList_Assign extends SimpleNode {
  public ArgList_Assign(int id) {
    super(id);
  }

  public ArgList_Assign(CCALTokeniser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALTokeniserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=60008b51de81c1a94fe79e9505f199fc (do not edit this line) */
