/* Generated By:JavaCC: Do not edit this line. CCALTokeniserVisitor.java Version 5.0 */
public interface CCALTokeniserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ProgramStart node, Object data);
  public Object visit(Var node, Object data);
  public Object visit(Const node, Object data);
  public Object visit(ID node, Object data);
  public Object visit(Number node, Object data);
  public Object visit(Function node, Object data);
  public Object visit(Return node, Object data);
  public Object visit(Type node, Object data);
  public Object visit(Param_list node, Object data);
  public Object visit(Parameters node, Object data);
  public Object visit(Main node, Object data);
  public Object visit(Statement node, Object data);
  public Object visit(Assign node, Object data);
  public Object visit(FunctionCall node, Object data);
  public Object visit(ArgList_Assign node, Object data);
  public Object visit(Plus node, Object data);
  public Object visit(Minus node, Object data);
  public Object visit(And node, Object data);
  public Object visit(Or node, Object data);
  public Object visit(Comp node, Object data);
  public Object visit(EQ node, Object data);
  public Object visit(NotEQ node, Object data);
  public Object visit(LESST node, Object data);
  public Object visit(LESSTEQ node, Object data);
  public Object visit(GREATT node, Object data);
  public Object visit(GREATTEQ node, Object data);
  public Object visit(Bool node, Object data);
}
/* JavaCC - OriginalChecksum=77bdb6a2e6c13dcdf26b06685bb6da34 (do not edit this line) */
