/* Generated By:JavaCC: Do not edit this line. CCALTokeniserTreeConstants.java Version 5.0 */
public interface CCALTokeniserTreeConstants
{
  public int JJTPROGRAMSTART = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;
  public int JJTCONST = 3;
  public int JJTID = 4;
  public int JJTNUMBER = 5;
  public int JJTFUNCTION = 6;
  public int JJTRETURN = 7;
  public int JJTTYPE = 8;
  public int JJTPARAM_LIST = 9;
  public int JJTPARAMETERS = 10;
  public int JJTMAIN = 11;
  public int JJTSTATEMENT = 12;
  public int JJTASSIGN = 13;
  public int JJTFUNCTIONCALL = 14;
  public int JJTARGLIST_ASSIGN = 15;
  public int JJTPLUS = 16;
  public int JJTMINUS = 17;
  public int JJTAND = 18;
  public int JJTOR = 19;
  public int JJTCOMP = 20;
  public int JJTEQ = 21;
  public int JJTNOTEQ = 22;
  public int JJTLESST = 23;
  public int JJTLESSTEQ = 24;
  public int JJTGREATT = 25;
  public int JJTGREATTEQ = 26;
  public int JJTBOOL = 27;


  public String[] jjtNodeName = {
    "ProgramStart",
    "void",
    "Var",
    "Const",
    "ID",
    "Number",
    "Function",
    "Return",
    "Type",
    "Param_list",
    "Parameters",
    "Main",
    "Statement",
    "Assign",
    "FunctionCall",
    "ArgList_Assign",
    "Plus",
    "Minus",
    "And",
    "Or",
    "Comp",
    "EQ",
    "NotEQ",
    "LESST",
    "LESSTEQ",
    "GREATT",
    "GREATTEQ",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=dbd9795cf1f2f58d7fff77214eac51e0 (do not edit this line) */
