/* Generated By:JJTree: Do not edit this line. LESSTEQ.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class LESSTEQ extends SimpleNode {
  public LESSTEQ(int id) {
    super(id);
  }

  public LESSTEQ(CCALTokeniser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCALTokeniserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e61bc4edf054885d84c6ed6916f68e63 (do not edit this line) */
